[package]
name = "huntsman_comm"
version = "0.1.0"
authors = ["Ivor Wanders <ivor@iwanders.net>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[lib]
name = "huntsman_comm"
path = "src/lib.rs"
crate-type = ["lib"]

[dependencies]
struct_helper = { path = "../struct_helper" }
